<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
        <script src="https://kit.fontawesome.com/4ead355834.js" crossorigin="anonymous"></script>
        <link rel="icon" href="public/img/favicon/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="public/css/normalize.css" type="text/css" />
        <link rel="stylesheet" href="public/css/admin_style.css" type="text/css" />
    </head>
    <body>
        <?php include $template; ?>
    </body>
</html>