<h1>Coffrets cadeaux</h1>
<p>Offrez un moment de plaisir à vos proches avec la carte cadeau.</p>
<!--<p>Vous pouvez désormais payer directement en ligne via nos paiements sécurisés.</p>
<p>A la réception du règlement, nous vous adresserons la carte cadeau par voie postale ou à retirer au restaurant.</p>

<p>Merci de nous préciser le message que nous devons insérer par mail à <a href="mailto:reservationssaintthomas@gmail.com">reservationssaintthomas@gmail.com</a>.</p>-->
<section class="gift_cards">
    <article class="gift_card_article">
        <h2>Coffret Saint Thomas</h2>
        <hr>
        <p>2 Kirs au Muscadet</p>
        <p>2 Menus Saint Thomas <em>(Entrée, Plat, Dessert)</em></p>
        <p>4 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>100€</h3>
    </article>
    <article class="gift_card_article">
        <h2>Coffret Maraîchin</h2>
        <hr>
        <p>2 Apéritifs maison</p>
        <p>2 Menus Maraîchin <em>(Entrée, Plat, Dessert)</em></p>
        <p>4 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>115€</h3>
    </article>
    <article class="gift_card_article">
        <h2>Coffret Découverte Express</h2>
        <hr>
        <p>2 Apéritifs maison</p>
        <p>2 Menus Découverte Express <em>(Entrée, Plat, Plateau de fromage, Dessert)</em></p>
        <p>4 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>130€</h3>
    </article>
    <article class="gift_card_article">
        <h2>Coffret Découverte</h2>
        <hr>
        <p>2 Coupes de Crémant</p>
        <p>2 Menus Découverte <em>(Entrée, Poisson, Viande, Plateau de fromages, Dessert)</em></p>
        <p>6 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>160€</h3>
    </article>
    <article class="gift_card_article">
        <h2>Coffret "À la Carte"</h2>
        <hr>
        <p>Vous choisissez le contenu de votre coffret cadeau.</p>
        <h3>Sur devis</h3>
    </article>
</section>