<h1>Menus</h1>
<!--<p></p>
<p></p>
<p></p>
<p></p>-->
<section class="menus">
    <article class="menu_article">
        <h2>Menu Saint Thomas</h2>
        <hr>
        <p>2 Kirs au Muscadet</p>
        <p>2 Menus Saint Thomas <em>(Entrée, Plat, Dessert)</em></p>
        <p>4 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>100€</h3>
    </article>
    <article class="menu_article">
        <h2>Menu Maraîchin</h2>
        <hr>
        <p>2 Apéritifs maison</p>
        <p>2 Menus Maraîchin <em>(Entrée, Plat, Dessert)</em></p>
        <p>4 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>115€</h3>
    </article>
    <article class="menu_article">
        <h2>Menu Découverte Express</h2>
        <hr>
        <p>2 Apéritifs maison</p>
        <p>2 Menus Découverte Express <em>(Entrée, Plat, Plateau de fromage, Dessert)</em></p>
        <p>4 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>130€</h3>
    </article>
    <article class="menu_article">
        <h2>Menu Découverte</h2>
        <hr>
        <p>2 Coupes de Crémant</p>
        <p>2 Menus Découverte <em>(Entrée, Poisson, Viande, Plateau de fromages, Dessert)</em></p>
        <p>6 Verres de vin</p>
        <p>2 Boissons chaudes</p>
        <h3>160€</h3>
    </article>
    <article class="menu_article">
        <h2>Coffret "À la Carte"</h2>
        <hr>
        <p>Vous choisissez le contenu de votre coffret cadeau.</p>
        <h3>Sur devis</h3>
    </article>
</section>