<h1>Gallerie photos</h1>
<section class="pictures_gallery">
    <article class="pictures">
        <!--<a href="public/img/pictures/gallery/1.jpg">-->
            <img src="public/img/pictures/gallery/1.jpg" alt="Devanture du restaurant" class="picture1" data-id="public/img/pictures/gallery/1.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/2.jpg">-->
            <img src="public/img/pictures/gallery/2.jpg" alt="Plaque extérieur maître restaurateur" class="picture2" data-id="public/img/pictures/gallery/2.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/3.jpg">-->
            <img src="public/img/pictures/gallery/3.jpg" alt="Graines de courges et amandes effilées" class="picture3" data-id="public/img/pictures/gallery/3.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/4.jpg">-->
            <img src="public/img/pictures/gallery/4.jpg" alt="Aromates" class="picture4" data-id="public/img/pictures/gallery/4.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/5.jpg">-->
            <img src="public/img/pictures/gallery/5.jpg" alt="Fleurs roses" class="picture5" data-id="public/img/pictures/gallery/5.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/6.jpg">-->
            <img src="public/img/pictures/gallery/6.jpg" alt="Fleurs jaunes" class="picture6" data-id="public/img/pictures/gallery/6.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/7.jpg">-->
            <img src="public/img/pictures/gallery/7.jpg" alt="Fleurs bleues" class="picture7" data-id="public/img/pictures/gallery/7.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/8.jpg">-->
            <img src="public/img/pictures/gallery/8.jpg" alt="Première salle intérieure du restaurant" class="picture8" data-id="public/img/pictures/gallery/8.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/9.jpg">-->
            <img src="public/img/pictures/gallery/9.jpg" alt="Table du restaurant à côté des alcools" class="picture9" data-id="public/img/pictures/gallery/9.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/10.jpg">-->
            <img src="public/img/pictures/gallery/10.jpg" alt="Vue grand angle de la première salle du restaurant" class="picture10" data-id="public/img/pictures/gallery/10.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/11.jpg">-->
            <img src="public/img/pictures/gallery/11.jpg" alt="David qui tient une fleur jaune" class="picture11" data-id="public/img/pictures/gallery/11.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/12.jpg">-->
            <img src="public/img/pictures/gallery/12.jpg" alt="David tenant 2 homards" class="picture12" data-id="public/img/pictures/gallery/12.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/13.jpg">-->
            <img src="public/img/pictures/gallery/13.jpg" alt="Entrée du restaurant avec ses pots de miel" class="picture13" data-id="public/img/pictures/gallery/13.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/14.jpg">-->
            <img src="public/img/pictures/gallery/14.jpg" alt="David et Magali, propriétaires du restaurant" class="picture14" data-id="public/img/pictures/gallery/14.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/15.jpg">-->
            <img src="public/img/pictures/gallery/15.jpg" alt="Table en terrasse" class="picture15" data-id="public/img/pictures/gallery/15.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/16.jpg">-->
            <img src="public/img/pictures/gallery/16.jpg" alt="Vue grand angle de la terrasse" class="picture16" data-id="public/img/pictures/gallery/16.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/17.jpg">-->
            <img src="public/img/pictures/gallery/17.jpg" alt="Petits pains sortant du four" class="picture17" data-id="public/img/pictures/gallery/17.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/18.jpg">-->
            <img src="public/img/pictures/gallery/18.jpg" alt="Couennes de porc grillées" class="picture18" data-id="public/img/pictures/gallery/18.jpg">
        <!--</a>-->
        
        <!--<a href="public/img/pictures/gallery/19.jpg">-->
            <img src="public/img/pictures/gallery/19.jpg" alt="Plaque de cuisson avec pains à burgers" class="picture19" data-id="public/img/pictures/gallery/19.jpg">
        <!--</a>-->
    </article>
</section>
<section class="full_screen_img" id="full_screen_img">
    <p>
        <a href="#" class="img_cross" id="img_cross" >
            <i class="fas fa-times"></i>
        </a>
    </p>
</section> 
<script type="text/javascript" src="public/js/pictures/pictures.js"></script>
<script type="text/javascript" src="public/js/pictures/main.js"></script>