<h1>Plats à emporter</h1>
<p>Menus disponibles uniquement sur réservation.</p>
<p>Merci de nous contacter par email ou téléphone :</p>
<p><a href="mailto:restolesaintthomas@orange.fr">restolesaintthomas@orange.fr</a></p>
<p><a href="tel:+33252490599">+33.2.51.49.05.99</a></p>
<p>Les menus sont à venir récupérer le vendredi et le samedi de 10h à 13h et peuvent se conserver plusieurs jours au frais.</p>
<section class="take_away_menus">
    <article class="take_away_menu_article">
        <h2>18, 19 et 20 décembre</h2>
        <h3>30€</h3>
        <hr>
        <p><span>Entrée:</span> Oeuf poché avec une crème de cèpes et pépite de foie gras, fricassée de chanterelles de Châteauneuf.</p>
        <p>-</p>
        <p><span>Plat:</span> Fricassée de joue de lotte, petits légumes au citron confit, raviole de crustacés sauce nantua.</p>
        <p>-</p>
        <p><span>Dessert:</span> Mokaccino et crémeux chocolat café.</p>
    </article>
    <article class="take_away_menu_article">
        <h2>18, 19 et 20 décembre</h2>
        <h3>30€</h3>
        <hr>
        <p><span>Entrée:</span> Oeuf poché avec une crème de cèpes et pépite de foie gras, fricassée de chanterelles de Châteauneuf.</p>
        <p>-</p>
        <p><span>Plat:</span> Fricassée de joue de lotte, petits légumes au citron confit, raviole de crustacés sauce nantua.</p>
        <p>-</p>
        <p><span>Dessert:</span> Mokaccino et crémeux chocolat café.</p>
    </article>
    <article class="take_away_menu_article">
        <h2>18, 19 et 20 décembre</h2>
        <h3>30€</h3>
        <hr>
        <p><span>Entrée:</span> Oeuf poché avec une crème de cèpes et pépite de foie gras, fricassée de chanterelles de Châteauneuf.</p>
        <p>-</p>
        <p><span>Plat:</span> Fricassée de joue de lotte, petits légumes au citron confit, raviole de crustacés sauce nantua.</p>
        <p>-</p>
        <p><span>Dessert:</span> Mokaccino et crémeux chocolat café.</p>
    </article>
    <article class="take_away_menu_article">
        <h2>18, 19 et 20 décembre</h2>
        <h3>30€</h3>
        <hr>
        <p><span>Entrée:</span> Oeuf poché avec une crème de cèpes et pépite de foie gras, fricassée de chanterelles de Châteauneuf.</p>
        <p>-</p>
        <p><span>Plat:</span> Fricassée de joue de lotte, petits légumes au citron confit, raviole de crustacés sauce nantua.</p>
        <p>-</p>
        <p><span>Dessert:</span> Mokaccino et crémeux chocolat café.</p>
    </article>
    <article class="take_away_menu_article">
        <h2>18, 19 et 20 décembre</h2>
        <h3>30€</h3>
        <hr>
        <p><span>Entrée:</span> Oeuf poché avec une crème de cèpes et pépite de foie gras, fricassée de chanterelles de Châteauneuf.</p>
        <p>-</p>
        <p><span>Plat:</span> Fricassée de joue de lotte, petits légumes au citron confit, raviole de crustacés sauce nantua.</p>
        <p>-</p>
        <p><span>Dessert:</span> Mokaccino et crémeux chocolat café.</p>
    </article>
    <article class="take_away_menu_article">
        <h2>18, 19 et 20 décembre</h2>
        <h3>30€</h3>
        <hr>
        <p><span>Entrée:</span> Oeuf poché avec une crème de cèpes et pépite de foie gras, fricassée de chanterelles de Châteauneuf.</p>
        <p>-</p>
        <p><span>Plat:</span> Fricassée de joue de lotte, petits légumes au citron confit, raviole de crustacés sauce nantua.</p>
        <p>-</p>
        <p><span>Dessert:</span> Mokaccino et crémeux chocolat café.</p>
    </article>
    <article class="take_away_menu_article">
        <h2>18, 19 et 20 décembre</h2>
        <h3>30€</h3>
        <hr>
        <p><span>Entrée:</span> Oeuf poché avec une crème de cèpes et pépite de foie gras, fricassée de chanterelles de Châteauneuf.</p>
        <p>-</p>
        <p><span>Plat:</span> Fricassée de joue de lotte, petits légumes au citron confit, raviole de crustacés sauce nantua.</p>
        <p>-</p>
        <p><span>Dessert:</span> Mokaccino et crémeux chocolat café.</p>
    </article>
</section>